vich_uploader:
    db_driver: orm

    mappings:
        language_images:
            uri_prefix: /uploads/languages
            upload_destination: '%kernel.project_dir%/public/uploads/languages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
